server:
  port: 8762

spring:
  application:
    name: projectservice
  cloud:
    stream:
      bindings:
        output:
          destination: zhuye
  datasource:
    url: jdbc:mysql://localhost:3306/ceshi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: siba01
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    feign:
      enabled: true
    sampler:
      probability: 1.0
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8865/eureka/
    registry-fetch-interval-seconds: 5


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: always
