spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ceshi?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
    username: root
    password: siba01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    database: 0
    port: 6379
  sleuth:
    sampler:
      probability: 1.0
    feign:
      enable: true
  zipkin:
    base-url: http://localhost:9411/
#    sender:
#      type: kafka
#    service:
#      name: ${spring.application.name}
  kafka:
    bootstrap-servers: localhost:9092
  main:
    allow-bean-definition-overriding: true

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

server:
  port: 8599
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8865/eureka/
